// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knbmqwhdjhkhfhiwtjco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuYm1xd2hkamhraGZoaXd0amNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDAxNTYsImV4cCI6MjA2MDcxNjE1Nn0.jhKsUjbXnoheJ3iKkIl4e_yQ6lWwboUFFEFzEcNFk0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);